---
title: "R Plots for Lateral Transport in the Mediterranean"
output: html_notebook
---





Notebook for making pretty figures from the lateral transport study.

```{r}
library(tidyverse)
library(ggmap)
library(cmocean)
```


Load data output from the batch analysis code.
```{r}

nemo_results_traj <- read_csv("../data/temp/nemo_results_traj.csv")
nemo_mean_ann_results <- read_csv("../data/temp/nemo_mean_ann_results.csv")
nemo_nov_may_results <- read_csv("../data/temp/nemo_nov_may_results.csv")
uk37_results_datatable <-read_csv("../data/temp/uk37_results_datatable.csv")
tex86_results_datatable <- read_csv("../data/temp/tex86_results_datatable.csv")

seas_matchup <- read.csv("../data/raw/Sediment_Locations_seas.csv")
```



Make the sinking speed into a factor and in the right order
```{r}
uk37_results_datatable <- uk37_results_datatable %>%
  transform(speed = gsub("^.{0,3}", "", speed)) %>%
  transform(speed = as.numeric(speed)) %>%
  filter(speed < 1000) %>%
  transform(speed = as.factor(speed))

tex86_results_datatable <- tex86_results_datatable %>%
  transform(speed = gsub("^.{0,3}", "", speed)) %>%
  transform(speed = as.numeric(speed)) %>%
  filter(speed < 1000) %>%
  transform(speed = as.factor(speed))
```


Match the keys for subbasin analysis
```{r}
seas_nemo_results <- left_join(nemo_mean_ann_results, select(seas_matchup, c(Location_key, Subbasin)), by = c("run_loc" = "Location_key"))
```

















```{r}
seas_check <- seas_nemo_results %>%
  ggplot(aes(
    x = site_lon,
    y = site_lat,
    color = Subbasin
  )) +
  geom_point() +
  annotation_map(map_data("world")) +
  coord_fixed() +
  scale_color_brewer(palette = "Dark2") +
  scale_x_continuous(name = NULL, limits = c(-10,40)) +
  scale_y_continuous(name = NULL, limits = c(30,48))

seas_check

ggsave("../results/figures/subbasin_map.pdf")
```


```{r}
depth_dist_seas <- seas_nemo_results %>%
  filter(speed == "Sp_6") %>%
  ggplot(aes(
    x = water_depth,
    y = mean_dist,
    color = Subbasin
  )) +
  geom_point() +
  scale_color_brewer(palette = "Dark2") +
  scale_x_continuous(name = "Water depth (m)") +
  scale_y_continuous(name = "Surface ocean to burial site distance (km)")

depth_dist_seas

ggsave("../results/figures/depth_dist_subbasin.pdf")
```

```{r}
depth_offset_seas <- seas_nemo_results %>%
  filter(speed == "Sp_6") %>%
  ggplot(aes(
    x = water_depth,
    y = offset_ann_sst,
    color = Subbasin
  )) +
  geom_point() +
  scale_color_brewer(palette = "Dark2") +
  scale_x_continuous(name = "Water depth (m)") +
  scale_y_continuous(name = expression(paste(SST[end] - SST[site], " (\u00b0C)"))) +
  ggtitle(expression("Transport bias (6 m" * d^{-1} * ")"))

depth_offset_seas

ggsave("../results/figures/depth_offset_subbasin.pdf")
```




```{r}
uk37_plots <- uk37_results_datatable %>%
  ggplot(aes(x = offset_nov_may_sst,
    y = proxy_offset_nov_may_site,
    color = speed)) +
  geom_point() +
  theme_minimal() +
  scale_color_brewer(palette = "Greys", direction = -1) +
  scale_x_continuous(name = expression(paste("Nov to May ", SST[end] - SST[site], " (\u00b0C)"))) +
  scale_y_continuous(name = expression(paste("Nov to May ", SST[UK37] - SST[site], " (\u00b0C)"))) +
  ggtitle(expression("Modeled Nov-May transport bias at " * U[37]^{K} *" sites"))

uk37_plots

ggsave("../results/figures/uk37_seasonal_transport_bias_offsets.pdf")
```






```{r}
uk37_dist_plot <- uk37_results_datatable %>%
  ggplot(aes(x = mean_dist_nov_may,
    y = proxy_offset_nov_may_site,
    color = speed)) +
  geom_point() +
  theme_minimal() +
  scale_color_brewer(palette = "Greys", direction = -1)

uk37_dist_plot

# ggsave("seasonal transport distance vs uk37 seasonal offset.pdf", uk37_plots)
```


```{r}
uk37_seasonal_offset_plot <- uk37_results_datatable %>%
  filter(wdepth > 500) %>%
  ggplot(aes(x = offset_nov_may_sst,
    y = proxy_offset_nov_may_site,
    color = speed)) +
  geom_point() +
  theme_minimal() +
  scale_color_brewer(palette = "Greys", direction = -1)

uk37_seasonal_offset_plot

# ggsave("seasonal transport bias vs uk37 seasonal offset - sites over 500m depth.pdf", uk37_plots)
```



```{r}
tex86_offset_plot <- tex86_ann_nemo_results %>%
  ggplot(aes(x = offset_ann_sst,
             y = proxy_offset_site_sst,
             color = speed)) +
  geom_point() 

tex86_offset_plot

ggsave("transport bias vs tex86 offset.pdf",tex86_offset_plot)
```




```{r}
tex86_offset_plot <- tex86_results_datatable %>%
  ggplot(aes(x = mean_dist,
             y = proxy_offset_site_sst,
             color = speed)) +
  geom_point() +
  theme_minimal() +
  scale_color_brewer(palette = "Greys", direction = -1)

tex86_offset_plot

# ggsave("travel distance vs tex86 offset.pdf",tex86_offset_plot)
```

```{r}
tex86_offset_depth_plot <- tex86_results_datatable %>%
  filter(water_depth > 1000) %>%
  ggplot(aes(x = offset_ann_sst,
             y = proxy_offset_site_sst,
             color = speed)) +
  geom_point() +
  theme_minimal() +
  scale_color_brewer(palette = "Greys", direction = -1)

tex86_offset_depth_plot

# ggsave("modeled vs tex86 offset - only deep sites.pdf",tex86_offset_plot)
```




```{r}
tex86_offset_dist_plot <- tex86_results_datatable %>%
  filter(water_depth > 1000) %>%
  ggplot(aes(x = mean_dist,
             y = proxy_offset_site_sst,
             color = speed)) +
  geom_point() +
  theme_minimal() +
  scale_color_brewer(palette = "Greys", direction = -1)

tex86_offset_plot

# ggsave("travel distance vs tex86 offset - only deep sites.pdf",tex86_offset_plot)
```


```{r}
tex86_offset_sp6_plot <- tex86_results_datatable %>%
  filter(speed == 6) %>%
  ggplot(aes(x = offset_ann_sst,
             y = proxy_offset_site_sst,
             color = water_depth)) +
  geom_point() +
  theme_minimal() +
  scale_color_cmocean("deep", direction = -1)

tex86_offset_sp6_plot

# ggsave("modeled vs tex86 offset - sp6.pdf",tex86_offset_plot)
```





```{r}
tex86_dist_sp6_plot <- tex86_results_datatable %>%
  filter(speed == 6) %>%
  ggplot(aes(x = mean_dist,
             y = proxy_offset_site_sst,
             color = water_depth)) +
  geom_point() +
  theme_minimal() +
  scale_color_cmocean("deep", direction = -1)

tex86_dist_sp6_plot

# ggsave("travel dist vs tex86 offset - sp6.pdf",tex86_offset_plot)
```





















